# Generated by Django 5.0.2 on 2024-12-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('point_load', models.FloatField(blank=True, null=True)),
                ('udl', models.FloatField(blank=True, null=True)),
                ('support_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Simply Supported', 'Simply Supported')], max_length=20)),
            ],
        ),
    ]
